/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./*.html"],
  darkMode: "class",
  safelist: [
    // Toutes les classes utilisées dans new_tab.html
    "-inset-0.5", "-z-10", "absolute", "backdrop-blur-xl",
    "bg-background", "bg-black/30", "bg-black/60",
    "bg-gradient-to-b", "bg-gradient-to-r", "bg-outline-variant/30",
    "bg-primary/10", "bg-primary/20", "bg-primary/5",
    "bg-surface-bright", "bg-surface-container", "bg-surface-container-highest",
    "bg-surface-container-low", "bg-surface-container-low/30", "bg-surface-container-low/90",
    "bg-transparent", "bg-white/60",
    "blur", "blur-[100px]", "blur-[120px]", "blur-[150px]",
    "border", "border-2", "border-b", "border-dashed", "border-none",
    "border-outline-variant/10", "border-outline-variant/15", "border-outline-variant/20",
    "border-primary", "border-primary/20", "border-t",
    "bottom-0", "bottom-8",
    "cursor-pointer", "duration-1000", "duration-500",
    "fixed", "flex", "flex-col", "flex-wrap", "focus:ring-0",
    "font-body", "font-headline", "font-label", "font-light", "font-medium",
    "from-black/40", "from-primary/0",
    "gap-1.5", "gap-2", "gap-3", "gap-4", "gap-6", "gap-8",
    "grid", "grid-cols-2", "group",
    "group-focus-within:opacity-100", "group-hover:rotate-90",
    "group-hover:scale-110", "group-hover:text-on-surface", "group-hover:text-primary",
    "h-3", "h-4", "h-7", "h-8", "h-10", "h-12", "h-24", "h-32", "h-40",
    "h-full", "h-screen", "h-[400px]", "h-[500px]", "h-[600px]",
    "hidden",
    "hover:bg-primary/5", "hover:bg-primary/10", "hover:bg-surface-container",
    "hover:border-primary/40", "hover:border-primary/60",
    "hover:scale-110", "hover:shadow-xl",
    "inset-0", "items-center", "items-start",
    "justify-between", "justify-center", "justify-items-center",
    "leading-none", "leading-tight", "left-0",
    "lg:grid-cols-5",
    "max-w-2xl", "max-w-4xl", "max-w-lg",
    "md:grid-cols-4", "md:text-9xl", "md:text-base",
    "min-w-[180px]",
    "ml-4", "mr-4", "mt-1", "mt-4", "mt-10", "mt-12", "mt-24", "mx-2",
    "object-cover",
    "opacity-0", "opacity-30", "opacity-50", "opacity-60", "opacity-80",
    "overflow-hidden", "overflow-x-auto", "overflow-y-auto",
    "p-1", "p-8", "pb-4", "pb-32",
    "placeholder-on-surface-variant/40",
    "pointer-events-auto", "pointer-events-none",
    "px-2", "px-4", "px-5", "px-6", "px-8",
    "py-1", "py-2", "py-3", "py-4",
    "relative", "right-0", "right-8",
    "rounded-2xl", "rounded-full", "rounded-lg", "rounded-xl",
    "select-none",
    "shadow-black/20", "shadow-lg",
    "text-2xl", "text-3xl", "text-4xl", "text-8xl",
    "text-[9px]", "text-[10px]",
    "text-base", "text-center", "text-gray-400", "text-gray-800",
    "text-lg", "text-on-surface", "text-on-surface-variant",
    "text-on-surface-variant/50", "text-primary", "text-primary/60",
    "text-sm", "text-white", "text-xl", "text-xs",
    "to-black/50", "to-primary/0",
    "top-0",
    "tracking-tighter", "tracking-wide", "tracking-wider", "tracking-widest",
    "tracking-[0.2em]", "tracking-[0.4em]",
    "transform", "transition", "transition-all", "transition-colors",
    "transition-opacity", "transition-transform", "translate-y-full",
    "uppercase",
    "via-primary/20", "via-transparent",
    "w-7", "w-8", "w-10", "w-12", "w-32", "w-full",
    "w-[1px]", "w-[400px]", "w-[500px]", "w-[600px]",
    "whitespace-nowrap", "z-50",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant":              "#3d4a43",
        "on-secondary-container":       "#96c2ad",
        "on-primary-container":         "#003121",
        "primary-container":            "#1ba47a",
        "on-tertiary-fixed":            "#410003",
        "on-surface":                   "#e5e2e1",
        "primary-fixed":                "#81f8c9",
        "secondary":                    "#a3d0ba",
        "primary-fixed-dim":            "#63dcae",
        "error-container":              "#93000a",
        "tertiary-fixed-dim":           "#ffb4ac",
        "surface-container-high":       "#2a2a2a",
        "on-tertiary-container":        "#570b0b",
        "on-background":                "#e5e2e1",
        "surface-container-highest":    "#353534",
        "on-primary-fixed-variant":     "#00513a",
        "surface-container-lowest":     "#0e0e0e",
        "surface-container-low":        "#1c1b1b",
        "background":                   "#131313",
        "surface-bright":               "#3a3939",
        "on-error":                     "#690005",
        "secondary-fixed":              "#bfedd6",
        "on-tertiary-fixed-variant":    "#7f2925",
        "on-error-container":           "#ffdad6",
        "on-primary":                   "#003827",
        "inverse-primary":              "#006c4e",
        "surface":                      "#131313",
        "surface-container":            "#201f1f",
        "inverse-surface":              "#e5e2e1",
        "secondary-container":          "#275140",
        "primary":                      "#63dcae",
        "tertiary-container":           "#dd7167",
        "surface-tint":                 "#63dcae",
        "outline":                      "#86948c",
        "on-secondary-fixed":           "#002115",
        "secondary-fixed-dim":          "#a3d0ba",
        "on-tertiary":                  "#601311",
        "on-secondary-fixed-variant":   "#254e3e",
        "on-primary-fixed":             "#002115",
        "surface-variant":              "#353534",
        "on-secondary":                 "#0a3728",
        "on-surface-variant":           "#bccac1",
        "tertiary-fixed":               "#ffdad6",
        "surface-dim":                  "#131313",
        "tertiary":                     "#ffb4ac",
        "error":                        "#ffb4ab",
        "inverse-on-surface":           "#313030",
      },
      fontFamily: {
        "headline": ["Space Grotesk", "Trebuchet MS", "sans-serif"],
        "body":     ["Manrope", "Helvetica Neue", "sans-serif"],
        "label":    ["Manrope", "Helvetica Neue", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg":      "0.25rem",
        "xl":      "0.5rem",
        "full":    "0.75rem",
      },
    },
  },
  plugins: [],
}
